# Generated by Django 4.2.16 on 2024-12-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scmg_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.IntegerField()),
                ('timestamp', models.TimeField()),
                ('conductivity', models.FloatField()),
                ('depth', models.FloatField()),
                ('battery', models.FloatField()),
                ('mayfly_temp', models.FloatField()),
                ('signal_percent', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
