# Generated by Django 4.2.16 on 2025-01-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NorthFork",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField()),
                ("conductivity", models.FloatField()),
                ("depth", models.FloatField()),
                ("temperature", models.FloatField()),
                ("battery", models.FloatField()),
                ("mayfly_temp", models.FloatField()),
                ("signal_percent", models.FloatField()),
            ],
            options={"db_table": "north_fork", "managed": False,},
        ),
    ]
